include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer:
  exclude:
    - build/**
    - lib/injectable/injectable.config.dart
    - test/.test_coverage.dart
    - lib/generated_plugin_registrant.dart
    - lib/**.g.dart
    - lib/**.config.dart
linter:
  rules:
    public_member_api_docs: false
