name: venom
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  api_service:
    git:
      url: https://github.com/hamidjalili59/api_service.git
      ref: main
  auto_route: ^7.7.0
  circular_countdown_timer: ^0.2.3
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  database_service:
    git:
      url: https://github.com/hamidjalili59/database_service.git
      ref: main
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  flutter_screenutil: ^5.9.0-beta
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  google_fonts: ^5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.1.2
  json_annotation: ^4.8.1
  logger: ^1.4.0
  ndialog: ^4.3.0
  path_provider: ^2.0.15
  timer_picker_spinner:
    git:
      url: https://github.com/hamidjalili59/timer_picker_spinner.git
      ref: main
  uuid: ^4.0.0-beta3-1

dev_dependencies:
  auto_route_generator: ^7.2.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.6
  json_serializable: ^6.6.1
  very_good_analysis: ^5.1.0

flutter_native_splash:
  color: "#000000"
  image: assets/icon/icon.png
  android_12:
    image: assets/icon/icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/
